"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url


# ----------------------------------------------------
# Base Directory
# ----------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------
# Environment Variables
# ----------------------------------------------------

# Local development:
#   Reads values from .env if it exists.
#
# Production on Render:
#   Render Environment Variables are already available
#   through os.environ.

load_dotenv(BASE_DIR / ".env")


# ----------------------------------------------------
# Security
# ----------------------------------------------------

SECRET_KEY = os.environ.get("SECRET_KEY")

if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set")


DEBUG = os.environ.get("DEBUG", "False").strip().lower() == "true"


# ALLOWED_HOSTS must contain hostnames only.
# Example:
#   ALLOWED_HOSTS=udhaya-electro.onrender.com,localhost,127.0.0.1

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# ----------------------------------------------------
# CSRF Trusted Origins
# ----------------------------------------------------

# These must include the full scheme (https://).
#
# Example:
#   CSRF_TRUSTED_ORIGINS=https://udhaya-electro.vercel.app

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# ----------------------------------------------------
# Installed Applications
# ----------------------------------------------------

INSTALLED_APPS = [

    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party Apps
    "rest_framework",
    "corsheaders",
    "django_filters",

    # Local Apps
    "accounts",
    "products",
    "categories",
    "contact",
    "material_requests",

    #storage
    "cloudinary_storage",
    "cloudinary",
]


# ----------------------------------------------------
# Middleware
# ----------------------------------------------------

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ----------------------------------------------------
# URL Configuration
# ----------------------------------------------------

ROOT_URLCONF = "config.urls"


# ----------------------------------------------------
# Templates
# ----------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ----------------------------------------------------
# WSGI
# ----------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"


# ----------------------------------------------------
# Database
# ----------------------------------------------------

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ----------------------------------------------------
# Password Validation
# ----------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ----------------------------------------------------
# Internationalization
# ----------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------
# Static Files
# ----------------------------------------------------

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# ----------------------------------------------------
# Media Files
# ----------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ----------------------------------------------------
# Cloudinary (media file storage)
# ----------------------------------------------------

# Set CLOUDINARY_URL in your environment, e.g.:
#   CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>
#
# When set, uploaded files go to Cloudinary instead of the local
# filesystem — required on Render since its disk is wiped on every
# deploy/restart.

if os.environ.get("CLOUDINARY_URL"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


# ----------------------------------------------------
# Default Primary Key
# ----------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ----------------------------------------------------
# Django REST Framework
# ----------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


# ----------------------------------------------------
# CORS Configuration
# ----------------------------------------------------

# This should contain the FULL frontend origin.
#
# Example:
#   CORS_ALLOWED_ORIGINS=https://udhaya-electro.vercel.app

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True


# ----------------------------------------------------
# File Upload Settings
# ----------------------------------------------------

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB