"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ----------------------------------------------------
# Base Directory
# ----------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / ".env")


# ----------------------------------------------------
# Security
# ----------------------------------------------------

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-$&g)df-je-for#-i@rjc_+&cn*lqi7yd3bw$l$s@h8t1n$@mj4")

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",") if os.environ.get("ALLOWED_HOSTS") else []


# ----------------------------------------------------
# Installed Applications
# ----------------------------------------------------

INSTALLED_APPS = [

    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party Apps
    "rest_framework",
    "corsheaders",
    "django_filters",

    # Local Apps
    "accounts",
    "products",
    "categories",
    "contact",
    "material_requests",
]


# ----------------------------------------------------
# Middleware
# ----------------------------------------------------

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ----------------------------------------------------
# URL Configuration
# ----------------------------------------------------

ROOT_URLCONF = "config.urls"


# ----------------------------------------------------
# Templates
# ----------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ----------------------------------------------------
# WSGI
# ----------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"


# ----------------------------------------------------
# Database
# ----------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ----------------------------------------------------
# Password Validation
# ----------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ----------------------------------------------------
# Internationalization
# ----------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------
# Static Files
# ----------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# ----------------------------------------------------
# Media Files
# ----------------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ----------------------------------------------------
# Default Primary Key
# ----------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ----------------------------------------------------
# Django REST Framework
# ----------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


# ----------------------------------------------------
# CORS Configuration
# ----------------------------------------------------

CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")

CORS_ALLOW_CREDENTIALS = True


# ----------------------------------------------------
# File Upload Settings
# ----------------------------------------------------

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760      # 10 MB

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760      # 10 MB